spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: nguyenvanhieu
    initialization-mode: always
    initialize: true
    continue-on-error: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379